[tool.poetry]
name = "c3-python"
version = "0.2.0"
description = ""
authors = ["Simon Warchol <simonwarchol@g.harvard.edu>"]
readme = "README.md"
packages = [{include = "c3_python"}]
repository = "https://github.com/python-poetry/poetry"


[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.24.2"
colorio = "^0.12.15"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
